
const fs = require('fs');
const content = fs.readFileSync('c:\\workspace\\oracle_custom\\oracle_to_pgsql.js', 'utf8');
const mockWindow = {};
const logic = new Function('window', content + '\nreturn OracleToPG;')(mockWindow);

const javaSrc = `
sbSql.append(" SELECT C.COMMON_DETAIL_CODE_NAME AS BANK_ACCT_TYPE_NAME \\n");
sbSql.append("     ,NVL(B.SA_GUBUN_CODE,?) AS SA_GUBUN_CODE \\n");
sbSql.append("     ,H.FUNCTION_NAME AS SA_GUBUN_NAME \\n");
sbSql.append("     ,B.BANK_ACCT_NICKNAME \\n");
sbSql.append("     ,B.BANK_ACCT_ID \\n");
sbSql.append("     ,D.KOR_NAME AS BELONG_DEPT_NAME \\n");
sbSql.append("     ,A.TRANS_DATE \\n");
sbSql.append("     ,A.TRANS_TIME \\n");
sbSql.append("     ,E.FUNCTION_NAME AS CURRENCY_NAME \\n");
sbSql.append("     ,A.INOUT_GUBUN_CODE \\n");
sbSql.append("     ,NVL(DECODE(A.INOUT_GUBUN_CODE,'20',A.TRANS_AMT,'51',A.TRANS_AMT * -1,'40',A.TRANS_AMT),0) AS IN_AMT \\n");
sbSql.append("     ,NVL(DECODE(A.INOUT_GUBUN_CODE,'30',A.TRANS_AMT,'30',A.TRANS_AMT,'52',A.TRANS_AMT * -1),0) AS OUT_AMT \\n");
sbSql.append("     ,NVL((DECODE(A.BALANCE_SIGNAL,'-',A.BALANCE_SIGNAL)||A.BALANCE_AMT),0) AS BALANCE \\n");
sbSql.append("     ,F.COMMON_DETAIL_CODE_NAME AS BANK_NAME \\n");
sbSql.append("     ,B.FC_CURRENCY_CODE \\n");
sbSql.append("     ,G.INDICATOR_NAME AS FC_CURRENCY_NAME \\n");
sbSql.append("     ,B.OLAS_ACCOUNT_CODE \\n");
sbSql.append("     ,A.OPP_DEPOSIT_HOLDER_NAME AS REMARKS \\n");
sbSql.append("     ,K.COMMON_DETAIL_CODE_NAME AS INOUT_GUBUN_NAME \\n");
sbSql.append(" FROM EGAS.COMMON_DETAIL_CODE_T F \\n");
sbSql.append("     ,EGAS.ES_INDICATOR_CODE_T G \\n");
sbSql.append("     ,EGAS.FUNCTION_CODE_T H \\n");
sbSql.append("     ,EGAS.BANK_ACCT_T B \\n");
sbSql.append("     ,EGAS.COMMON_DETAIL_CODE_T C \\n");
sbSql.append("     ,EGAS.AUTHORIZATION_CODE_T D \\n");
sbSql.append("     ,EGAS.FUNCTION_CODE_T E \\n");
sbSql.append("     ,EGAS.CMS_TRANS_LIST_T A \\n");
sbSql.append("     ,EGAS.COMMON_DETAIL_CODE_T K \\n");
sbSql.append(" WHERE 1 = 1 \\n");
sbSql.append(" AND A.USE_FLAG = '1' \\n");
sbSql.append(" AND B.USE_FLAG = '1' \\n");
sbSql.append(" AND B.APPROVAL_YN = '1' \\n");
sbSql.append(" AND B.BANK_ACCT_SEQ = A.BANK_ACCT_SEQ \\n");
sbSql.append(" AND C.COMMON_DETAIL_CODE = B.BANK_ACCT_TYPE_CODE \\n");
sbSql.append(" AND C.COMMON_CODE = '0022' \\n");
sbSql.append(" AND D.TYPE = '400' \\n");
sbSql.append(" AND D.CODE = B.MNGT_DEPT_CODE \\n");
sbSql.append(" AND E.FUNCTION_CODE = B.CURRENCY_CODE \\n");
sbSql.append(" AND E.CATEGORY_CODE = '0004' \\n");
sbSql.append(" AND F.COMMON_DETAIL_CODE = B.BANK_CODE \\n");
sbSql.append(" AND F.COMMON_CODE = '0021' \\n");
sbSql.append(" AND G.FINANCIAL_CODE(+) = '03' \\n");
sbSql.append(" AND G.INDICATOR_CODE(+) = B.FC_CURRENCY_CODE \\n");
sbSql.append(" AND NVL(B.SA_GUBUN_CODE,?) = H.FUNCTION_CODE(+) \\n");
sbSql.append(" AND H.CATEGORY_CODE(+) = '0013' \\n");
sbSql.append(" AND K.COMMON_DETAIL_CODE = A.INOUT_GUBUN_CODE \\n");
sbSql.append(" AND K.COMMON_CODE = '0103' \\n");
`;

const extracted = logic.extract(javaSrc);
const pg = logic.transform(extracted);
console.log("--- Transformed PG SQL ---");
console.log(pg);
